[target.msgpack_example]
type = "executable"
sources = ["msgpack.cpp"]
include-directories = ["../include"]
compile-features = ["cxx_std_23"]

[target.msgpack_rpc_example]
type = "executable"
sources = ["msgpack_rpc.cpp"]
include-directories = ["../include"]
compile-features = ["cxx_std_23"]